### ISSUE TITLE
Add install section in README.md

### ISSUE THREAD

**Issue by jdzak** [nathanmarks/babel-plugin-transform-react-es6-displayname#1]
I'm trying to figure out how to reference this plugin in my .babelrc, but haven't been successful. Any suggestions?

Maybe adding a section in the README.md for installation would be helpful for people trying to use this plugin.

**Comment by nathanmarks** [comment]
Hey @jdzak , can you show me your `.babelrc`? PS, since setting up this plugin, I actually decided to add my own static property to classes in order to identify them within my own code instead of depending on `displayName` which is really for dev debug purposes.

**Comment by jdzak** [comment]
Thanks for the response, I figured out what the problem was. In my `.babelrc` I used the plugin name from the REAMDE `babel-transform-react-es6-class-displayname` instead of the project name `babel-plugin-transform-react-es6-displayname.
